config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'irgls#index'
  resources :irgls do
    resources :comments, only: :create
    collection do
      get 'search'
    end
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :irgl
  belongs_to :user
end

app/models/irgl.rb
class Irgl < ApplicationRecord
  validates :spot, presence: true
  validates :ship_no, presence: true
  validates :status, presence: true
  validates :remarks, presence: true
  belongs_to :user
  has_many :comments

  def self.search(search)
    if search != ''
      Irgl.where('text LIKE(?)', "%#{search}%")
    else
      Irgl.all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :irgls
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    redirect_to "/irgls/#{comment.irgl.id}"
  end

  private

  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, irgl_id: params[:irgl_id])
  end
end

app/controllers/irgls_controller.rb
class IrglsController < ApplicationController
  before_action :set_irgl, only: [:edit, :show]
  before_action :move_to_index, except: [:index, :show, :search]

  def index
    @irgls = Irgl.includes(:user).order('created_at DESC')
  end

  def new
    @irgl = Irgl.new
  end

  def create
    Irgl.create(irgl_params)
  end

  def destroy
    irgl = Irgl.find(params[:id])
    irgl.destroy
  end

  def edit
  end

  def update
    irgl = Irgl.find(params[:id])
    irgl.update(irgl_params)
  end

  def show
    @comment = Comment.new
    @comments = @irgl.comments.includes(:user)
  end

  def search
    @irgls = Irgl.search(params[:keyword])
  end

  private

  def irgl_params
    params.require(:irgl).permit(:spot, :ship_no, :status, :remarks).merge(user_id: current_user.id)
  end

  def set_irgl
    @irgl = Irgl.find(params[:id])
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @name = user.name
    @irgls = user.irgls
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/irgls_helper.rb
module IrglsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/irgls/_form.html.erb
    <%= form_with(model: irgl, local: true) do |form| %>
    <%= form.text_area :spot, placeholder: "spot", rows: "10" %>
    <%= form.text_area :ship_no, placeholder: "ship_no", rows: "10" %>
    <%= form.text_area :status, placeholder: "status", rows: "10" %>
    <%= form.text_area :remarks, placeholder: "remarks", rows: "10" %>
      <%= form.submit "イレギュラーの処理状況を投稿する" %>
    <% end %>

app/views/irgls/_irgl.html.erb
    <div class="content_post">
    
        <div class="more">
       <a>編集・削除する</a>
       <br>※自分の投稿のみ可</br>
        
           <% if user_signed_in? && current_user.id == irgl.user_id %>
         <li>
            <%= link_to '編集', edit_irgl_path(irgl.id), method: :get %>
          </li>
          <li>
            <%= link_to '削除', "/irgls/#{irgl.id}", method: :delete %>
          </li>
           <% end %>
      </div>

      <br><%= irgl.spot %></br>
      <br><%= irgl.ship_no %></br>
      <br><%= irgl.status %></br>
      <br><%= irgl.remarks %></br>
      <span class="name">
      <a href="">
      <span>投稿者</span><%= irgl.user.name %>
      </a>
      </span>
    </div>

app/views/irgls/create.html.erb
<div class="contents row">
  <div class="success">
    <h3>投稿が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/irgls/destroy.html.erb
<div class="contents row">
  <div class="success">
    <h3>削除が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/irgls/edit.html.erb
<div class="contents row">
  <div class="container">
    <h3>編集する</h3>
   <%= render partial: "form", locals: { irgl: @irgl } %>
  </div>
</div>

app/views/irgls/index.html.erb
<div class="contents row">
  <% @irgls.each do |irgl| %>
<%= render partial: "irgl", locals: { irgl: irgl } %>
  <% end %>
</div>

app/views/irgls/new.html.erb
<div class="contents row">
  <div class="container">
    <h3>イレギュラーの処理状況を投稿する</h3>
 <%= render partial: "form", locals: { irgl: @irgl } %>
  </div>
</div>

app/views/irgls/show.html.erb
<div class="contents row">
  <div class="content_post">
   
   <% if user_signed_in? && current_user.id == @irgl.user_id %>
    <div class="more">
      <span><%= image_tag 'arrow_top.png' %></span>
      <ul class="more_list">
        <li>
          <%= link_to '編集', edit_irgl_path(@irgl.id), method: :get %>
        </li>
        <li>
          <%= link_to '削除', irgl_path(@irgl.id), method: :delete %>
        </li>
      </ul>
    </div>
     <% end %>
     
    <p><%= @irgl.spot %></p>
   <span class="name">
      <a href="/users/<%= @irgl.user.id %>">
        <span>投稿者</span><%= @irgl.user.name %>
      </a>
    </span>
  </div>

  <div class="container">
    <% if user_signed_in? %>
      <%= form_with(model: [@irgl, @comment], local: true) do |form| %>
        <%= form.text_area :text, placeholder: "コメントする", rows: "2" %>
        <%= form.submit "コメントを投稿する" %>
      <% end %>
    <% else %>
      <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p>
      </strong>
    <% end %>
     <div class="comments">
      <h4>＜コメント一覧＞</h4>
      <% @comments.each do |comment| %>
        <p>
          <strong><%= link_to comment.user.name, "/users/#{comment.user_id}" %>:</strong>
          <%= comment.text %>
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/irgls/update.html.erb
<div class="contents row">
  <div class="success">
    <h3>更新が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>空港専用イレギュラー対応アプリ</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header class="header">
      <div class="header__bar row">
        <h1 class="grid-6"><a href="/">Irregular Application</a></h1>
          <% if user_signed_in? %>
          <div class="user_nav grid-6">
            <%= link_to "マイページ", "/users/#{current_user.id}" %>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
            <%= link_to "投稿する", new_irgl_path, class: "post" %>
          </div>
        <% else %>
          <div class="grid-6">
            <%= link_to "ログイン", new_user_session_path, class: "post" %>
            <%= link_to "新規登録", new_user_registration_path, class: "post" %>
          </div>
        <% end %>
      </div>
    </header>

    <body>
    <h1>user</h1>
     <h1>user name</h1>
    </div>

    </body>

    <%= yield %>


     <footer>
      <p>
        Copyright Irgl App 2022.
      </p>
    </footer>
  </body>
</html>

app/views/users/show.html.erb
<div class="contents row">
  <p><%= @name %>さんの投稿一覧</p>
  <% @irgls.each do |irgl| %>
 <%= render partial: "irgls/irgl", locals: { irgl: irgl } %>
  <% end %>
</div>